name: example_for_web_document_scanner
description: Web Document Scanner
version: 0.0.1
homepage: https://www.linkedin.com/in/resam/
repository: https://github.com/reesaam/web_document_scanner
funding:
  - https://resam.site

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

#  web_document_scanner: 0.0.1
  web_document_scanner:
    path: ../

dev_dependencies:
  lints: ^4.0.0
  test: ^1.24.0

flutter:
  assets:
    - ../assets/