name: Web Document Scanner Package Release

on:
  push:
    tags:
      - 'v*.*.*'

permissions:
  contents: write
  pull-requests: write

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Dart
        uses: dart-lang/setup-dart@v1
        with:
          sdk: '3.8.1' # stable

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.32.8' #'stable'

      - name: Clean Build
        run: flutter clean

      - name: Get dependencies
        run: flutter pub get

      - name: pubspec Version Check
        run: |
          TAG_VERSION=${GITHUB_REF#refs/tags/v}
          FILE_VERSION=$(grep '^version:' pubspec.yaml | awk '{print $2}')
          if [ "$TAG_VERSION" != "$FILE_VERSION" ]; then
            echo "❌ Tag version ($TAG_VERSION) does not match pubspec.yaml version ($FILE_VERSION)"
            exit 1
          fi

      - name: ChangeLog Check
        run: |
          VERSION_TAG=${GITHUB_REF#refs/tags/v}
          if grep -q "$VERSION_TAG" CHANGELOG.md; then
            echo "✅ CHANGELOG.md contains version $VERSION_TAG"
          else
            echo "❌ CHANGELOG.md does not mention version $VERSION_TAG"
            exit 1
          fi

      - name: Release Branch Creation
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          VERSION_TAG=${GITHUB_REF#refs/tags/}
          RELEASE_BRANCH="releases/$VERSION_TAG"

          git checkout -b "$RELEASE_BRANCH"
          git push origin "$RELEASE_BRANCH"

      - name: Merge Release Branch to Main Feasibility
        run: |
          VERSION_TAG=${GITHUB_REF#refs/tags/}
          RELEASE_BRANCH="releases/$VERSION_TAG"

          git fetch origin main
          git checkout main

          if git merge-tree $(git merge-base origin/main "$RELEASE_BRANCH") origin/main "$RELEASE_BRANCH" | grep -q "<<<<<<<"; then
            echo "❌ Merge conflicts detected. Deleting release branch."
            git push origin --delete "$RELEASE_BRANCH"
            exit 1
          else
            echo "✅ Release branch can be merged cleanly into main."
          fi

#      - name: Code Analyze
#        run: dart analyze

#      - name: Tests Run
#        run: dart test

      - name: Check Dry-run Publish
        run: dart pub publish --dry-run

#      - name: pub.dev Authentication
#        run: |
#          echo "$PUB_DEV_TOKEN" > ~/.pub-cache/pub-credentials.json
#        env:
#          PUB_DEV_TOKEN: ${{ secrets.PUB_DEV_TOKEN }}
#
#      - name: Package Publish
#        run: dart pub publish --force

      - name: Package Publish
        uses: k-paxian/dart-package-publisher@v1.5.1
        with:
          credentialJson: ${{ secrets.CREDENTIAL_JSON }}
          flutter: true
          skipTests: true

      - name: Create and Merge (squash) Pull Request to main
        run: |
          VERSION_TAG=${GITHUB_REF#refs/tags/}
          RELEASE_BRANCH="releases/$VERSION_TAG"

          sudo apt update
          sudo apt install gh -y
          echo "${{ secrets.GITHUB_TOKEN }}" | gh auth login --with-token

          gh pr create \
            --base main \
            --head "$RELEASE_BRANCH" \
            --title "Release $VERSION_TAG" \
            --body "Automated release PR for version $VERSION_TAG"

          PR_NUMBER=$(gh pr list --head "$RELEASE_BRANCH" --json number --jq '.[0].number')

          gh pr merge "$PR_NUMBER" --squash --admin

