name: publish to pub.dev

on:
  push:
    tags:
      - 'v.*.*.*'

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Dart
        uses: dart-lang/setup-dart@v1
        with:
          sdk: stable

      - name: Get Dependencies
        run: flutter pub get

      - name: Create release branch
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          VERSION_TAG=${GITHUB_REF#refs/tags/}
          RELEASE_BRANCH="releases/$VERSION_TAG"
          git checkout -b "$RELEASE_BRANCH"
          git push origin "$RELEASE_BRANCH"

      - name: Create pull request to main
        run: |
          VERSION_TAG=${GITHUB_REF#refs/tags/}
          RELEASE_BRANCH="releases/$VERSION_TAG"
          
          # Install GitHub CLI
          sudo apt-key adv --keyserver keyserver.ubuntu.com --recv-key C99B11DEB97541F0
          sudo apt-add-repository https://cli.github.com/packages
          sudo apt update
          sudo apt install gh -y
          
          # Authenticate GitHub CLI
          echo "${{ secrets.GITHUB_TOKEN }}" | gh auth login --with-token
          
          # Create pull request
          gh pr create \
            --base main \
            --head "$RELEASE_BRANCH" \
            --title "Release $VERSION_TAG" \
            --body "Automated release PR for version $VERSION_TAG"

      - name: Authenticate with pub.dev
        run: |
          mkdir -p ~/.pub-cache
          echo "$PUB_DEV_TOKEN" > ~/.pub-cache/credentials.json
        env:
          PUB_DEV_TOKEN: ${{ secrets.PUB_DEV_TOKEN }}

      - name: Publish package
        run: dart pub publish
