name: publish to pub.dev

on:
  push:
    tags:
      - 'v.*.*.*'

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Dart
        uses: dart-lang/setup-dart@v1
        with:
          sdk: stable

      - name: Get Dependencies
        run: dart pub get

      - name: Authenticate with pub.dev
        run: |
          mkdir -p ~/.pub-cache
          echo "$PUB_DEV_TOKEN" > ~/.pub-cache/credentials.json
        env:
          PUB_DEV_TOKEN: ${{ secrets.PUB_DEV_TOKEN }}

      - name: Publish package
        run: dart pub publish
